FROM fedora:34

# docker build --build-arg http_proxy=http://10.158.100.9:8080 --build-arg https_proxy=http://10.158.100.9:8080

ENV TZ=Asia/Shanghai
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN dnf install -y vim git-core tmux zsh
COPY ./rootfs/home/felixdu/.tmux.conf /home/felixdu/
COPY ./rootfs/home/felixdu/.gitconfig /home/felixdu/

# RUN groupadd felixdu
RUN useradd -ms /usr/bin/zsh felixdu
RUN chown -R felixdu:felixdu /home/felixdu

RUN mkdir -p /etc/sudoers.d
RUN echo "felixdu ALL=(root) NOPASSWD:ALL" > /etc/sudoers.d/felixdu && chmod 0440 /etc/sudoers.d/felixdu

# Change user to felixdu; following commands are run with user felixdu
USER felixdu
WORKDIR /home/felixdu

RUN sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
COPY ./rootfs/home/felixdu/.zshrc $WORKDIR
