FROM fedora:34

# docker build --build-arg http_proxy=http://10.158.100.9:8080 --build-arg https_proxy=http://10.158.100.9:8080

ENV TZ=Asia/Shanghai
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN dnf install -y vim git-core tmux zsh
COPY ./rootfs/home/infi/.tmux.conf /home/infi/
COPY ./rootfs/home/infi/.gitconfig /home/infi/

# RUN groupadd infi
RUN useradd -ms /usr/bin/zsh infi
RUN chown -R infi:infi /home/infi

RUN mkdir -p /etc/sudoers.d
RUN echo "infi ALL=(root) NOPASSWD:ALL" > /etc/sudoers.d/infi && chmod 0440 /etc/sudoers.d/infi

# Change user to infi; following commands are run with user infi
USER infi
WORKDIR /home/infi

RUN sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
COPY ./rootfs/home/infi/.zshrc $WORKDIR
