FROM ubuntu:20.04

ENV http_proxy=http://10.158.100.7:8080
ENV https_proxy=http://10.158.100.7:8080
ENV HTTP_PROXY=http://10.158.100.7:8080
ENV HTTPS_PROXY=http://10.158.100.7:8080

ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Asia/Shanghai
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

#RUN apt-get update && apt-get -y install vim universal-ctags global fzf ripgrep \
#                build-essential clangd \
#		zsh git tmux htop nodejs npm nux-tools curl wget \
#		openssh-client \
#		golang cppman python3-pip i3 tigervnc-standalone-server

RUN apt-get update && apt-get -y install vim tigervnc-standalone-server i3 zsh

COPY ./rootfs /

#RUN groupadd infi
RUN useradd -ms /usr/bin/zsh infi
RUN chown -R infi:infi /home/infi

RUN mkdir -p /etc/sudoers.d
RUN echo "infi ALL=(root) NOPASSWD:ALL" > /etc/sudoers.d/infi && chmod 0440 /etc/sudoers.d/infi
#RUN echo "infi ALL=(root) NOPASSWD:ALL" > /etc/sudoers.d/docker && chmod 0440 /etc/sudoers.d/docker


# Change user to infi; following commands are run with user infi
USER infi
WORKDIR /home/infi

RUN sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
