#!/bin/sh

unset SESSION_MANAGER
unset DBUS_SESSION_BUS_ADDRESS
#exec /etc/X11/xinit/xinitrc

xrdb -merge $HOME/.Xresources
userclientrc=$HOME/.xinitrc
systemclientrc=/etc/X11/xinit/xinitrc

xset +fp /usr/share/fonts
xset fp rehash

export _JAVA_AWT_WM_NONREPARENTING=1
export XKL_XMODMAP_DISABLE=1

#exec gnome-session
#/home/infi/src/dwm/dwm-bar/dwm_bar.sh
#exec twm
exec i3
#exec startlxde
